name: CI

on: [push, pull_request]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.TRAMVAI_GH_PAGES_PAT }}

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        platform:
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: bash
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    steps:
      - name: Checkout Repository
        if: ${{ (matrix.platform.os != 'windows-latest') }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Use Nodejs ${{ matrix.node-version }}
        if: ${{ (matrix.platform.os != 'windows-latest') }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: debugging
        run: echo NODEVERSION=[${{ matrix.node-version }}] OS=[${{ matrix.platform.os }}]

      # skip tests on node at Windows, because npm install npm -g fails
      - name: Use latest npm
        if: ${{ (matrix.platform.os != 'windows-latest') }}
        run: npm i -g npm@latest

      - name: Install dependencies
        if: ${{ (matrix.platform.os != 'windows-latest') }}
        run: npm ci

      - name: Run Tests
        if: ${{ (matrix.platform.os != 'windows-latest') }}
        run: npm test -- -c -t0

      - name: Check release
        if: ${{ (matrix.platform.os != 'windows-latest') }}
        run: npm run release:dry
