name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        platform:
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: bash
          - os: windows-latest
            shell: powershell
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    steps:
      - name: Checkout Repository
        if: ${{ (matrix.platform.os != 'windows-latest') }}
        uses: actions/checkout@v3

      - name: Use Nodejs ${{ matrix.node-version }}
        if: ${{ (matrix.platform.os != 'windows-latest') }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: debugging
        run: echo NODEVERSION=[${{ matrix.node-version }}] OS=[${{ matrix.platform.os }}]

      # skip tests on node <16 on Windows, because npm install npm -g fails
      - name: Use latest npm
        if: ${{ (matrix.platform.os != 'windows-latest') }}
        run: npm i -g npm@latest

      - name: Install dependencies
        if: ${{ (matrix.platform.os != 'windows-latest') }}
        run: npm install

      - name: Run Tests
        if: ${{ (matrix.platform.os != 'windows-latest') }}
        run: npm test -- -c -t0
