name: "various tidying up tasks to silence nagging"

on:
  push:
    branches:
      - main

jobs:
  makework:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 20.x
      - name: put repo in package.json
        run: node .github/workflows/package-json-repo.js
      - name: check in package.json if modified
        run: |
          bash -x .github/workflows/commit-if-modified.sh \
            "tramvai-conductor@users.noreply.github.com" \
            "Tramvai Conductor" \
            "chore: add repo to package.json" \
            package.json package-lock.json
      - name: put all dates in license copyright line
        run: bash .github/workflows/copyright-year.sh
      - name: check in licenses if modified
        run: |
          bash .github/workflows/commit-if-modified.sh \
            "tramvai-conductor@users.noreply.github.com" \
            "Tramvai Conductor" \
            "chore: add copyright year to license" \
            LICENSE*
