name: "various tidying up tasks to silence nagging"

on:
  push:
    branches:
      - main

jobs:
  makework:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 20.x

      - name: put repo in package.json
        run: node .github/workflows/package-json-repo.js

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        with:
          commit_user_name: Tramvai Conductor
          commit_user_email: tramvai-conductor@users.noreply.github.com
          commit_message: "chore: add repo to package.json"
          file_pattern: "package.json package-lock.json"

      - name: put all dates in license copyright line
        run: bash .github/workflows/copyright-year.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        with:
          commit_user_name: Tramvai Conductor
          commit_user_email: tramvai-conductor@users.noreply.github.com
          commit_message: "chore: add copyright year to license"
          file_pattern: "LICENSE*"
