name: Pull request

on: [pull_request]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.TRAMVAI_GH_PAGES_PAT }}

jobs:
  build-and-test:
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        platform:
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: bash
          # Skip workflow on Windows due to `npm install npm -g` fails
          #- os: windows-latest
          #  shell: bash
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Use latest npm
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test -- -c -t0

      - name: Check release
        run: npm run release:dry
