name: "size"
on:
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v4
      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.TRAMVAI_GH_PAGES_PAT }}
